language: node_js
node_js: "17"
os:
  - linux
dist: trusty
osx_image: xcode8.3
sudo: false

before_install:
  - sudo apt-get install python

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

addons:
  apt:
    packages:
      - fakeroot
      - rpm

install:
  - npm install
  - npm update

script:
  - npm run lint
  - if test -z "$TRAVIS_TAG"; then npm run make; fi
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "test"
  skip_cleanup: true
  on:
    branch: main
    tags: false
